name: Build and Release Packages

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release (true/false)" # If false, publish artifacts only.
        required: false
        default: "true"

jobs:
  build-and-release:
    name: Build and Release Packages
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: "alpine:latest"
      options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate TAG_NAME
        id: set_tag_name
        run: |
          TAG_NAME="v${GITHUB_RUN_NUMBER}-$(date +'%Y%m%d%H%M%S')"
          echo "$TAG_NAME" > tag_name.txt
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Upload TAG_NAME Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tag-name
          path: tag_name.txt

      - name: Download Latest AliceLinux
        run: |
          set -x
          apk update
          apk upgrade
          apk add curl tar

          # Get the latest release tag from Codeberg
          LATEST_TAG=$(curl -s https://codeberg.org/api/v1/repos/emmett1/alicelinux/releases/latest | grep -o '"tag_name":"[^"]*' | cut -d'"' -f4)

          mkdir ./alice
          wget -qO- "https://codeberg.org/emmett1/alicelinux/releases/download/${LATEST_TAG}/alicelinux-rootfs-${LATEST_TAG}.tar.xz" | tar xJvf - -C ./alice

          # Enter chroot and perform operations
          ./alice/usr/bin/apkg-chroot ./alice sh -s <<'EOF'
          echo "Welcome to AliceLinux"

          # Set up repositories
          git clone --depth=1 https://codeberg.org/emmett1/alicelinux /var/lib/alicelinux
          mkdir -p /var/cache/pkg /var/cache/src /var/cache/work

          echo 'export CFLAGS="-O2 -march=x86-64-v3 -pipe"' >> /etc/apkg.conf
          echo 'export CXXFLAGS="$CFLAGS"' >> /etc/apkg.conf
          echo 'export MAKEFLAGS="-j$(nproc)"' >> /etc/apkg.conf
          echo 'export NINJAJOBS="$(nproc)"' >> /etc/apkg.conf
          echo 'APKG_REPO="/var/lib/alicelinux/repos/core /var/lib/alicelinux/repos/extra /var/lib/alicelinux/repos/wayland /var/lib/alicelinux/repos/xorg"' >> /etc/apkg.conf
          echo 'APKG_PACKAGE_DIR=/var/cache/pkg' >> /etc/apkg.conf
          echo 'APKG_SOURCE_DIR=/var/cache/src' >> /etc/apkg.conf
          echo 'APKG_WORK_DIR=/var/cache/work' >> /etc/apkg.conf

          echo "xplshn/alicelinux-bin" > /etc/hostname
          export APKG_NOPROMPT=1

          apkg-reposync
          apkg -U || true
          apkg -I meson cmake pkgconf libtool automake perl ccache || true
          apkg -I $(apkg -s) || true
          apkg-clean || true
          EOF

      - name: Create and Save Rootfs Tarball
        run: |
          tar -cJf alicelinux-rootfs-${{ env.TAG_NAME }}.tar.xz -C ./alice .
          mkdir -p ${{ github.workspace }}/artifacts
          mv alicelinux-rootfs-${{ env.TAG_NAME }}.tar.xz ${{ github.workspace }}/artifacts/

      - name: Copy Package Files
        run: |
          mkdir -p ${{ github.workspace }}/packages
          cp ./alice/var/cache/pkg/*.spm ${{ github.workspace }}/packages/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ github.workspace }}/artifacts/alicelinux-rootfs-${{ env.TAG_NAME }}.tar.xz
            ${{ github.workspace }}/packages/*.spm

      - name: Create Release (if enabled)
        if: ${{ github.event.inputs.release == 'true' }}
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: "Package Release - ${{ env.TAG_NAME }}"
          tag_name: "${{ env.TAG_NAME }}"
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            ${{ github.workspace }}/artifacts/alicelinux-rootfs-${{ env.TAG_NAME }}.tar.xz
            ${{ github.workspace }}/packages/*.spm
